### ISSUE TITLE
Question / Any plan to make it available through composer ?

### ISSUE THREAD

**Issue by jesuismaxime** [olach/kirby3-relationship#1]
The question says it all !

**Comment by olach** [comment]
Yes absolutely! I will look into it.

**Comment by olach** [comment]
You can now install this plugin using Composer: `composer require olach/relationship`

Documentation for usage is coming soon. But most of the options for the regular [Multiselect field](https://getkirby.com/docs/reference/panel/fields/multiselect) also apply to this field.
