### ISSUE TITLE
Auto sort selected entries?

### ISSUE THREAD

**Issue by trych** [olach/kirby3-relationship#14]
Hi there,

is there any way to automatically sort the selected entries (like by title or any other page field) *in the panel*?

Thanks!

**Comment by olach** [comment]
Hi. Sorry, no that is not possible at the moment in this plugin.

The native multiselect field has an option to sort the selected entries according to their position in the dropdown. If that is what you are looking for, maybe it's possible to use that field instead? These two fields should be interchangeable if you want to try.

https://getkirby.com/docs/reference/panel/fields/multiselect

**Comment by trych** [comment]
Hi there,
in my specific case I prefer using the relationship field. I guess I'll have to live without panel sorting then for now.
Thanks for the quick response!
